[tool.poetry]
name = "yaht"
version = "0.1.0"
description = "Yet Another Hyperparameter Tweaker"
authors = ["basilisk <d0ix9oqh@anonaddy.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
